### PR TITLE
feat: add adjustStyleLoaders

### LINKED ISSUE #81: Customizing autoprefixer configuration
I would like to change the autoprefixer configuration to include `grid: 'autoplace'`.  Is there a way to do that with customize-cra?  I tried reloading autoprefixer as the following, but with no success:  `addPostcssPlugins([require('autoprefixer')({ grid: 'autoplace' })])`.

### PR DESCRIPTION
**Pull request by billypon**
closes #81

### CODE REVIEW

**Comment by with-heart** [comment]
Hi @billypon, could you add a fake use case to the callback in `api.md`? The callback you've added doesn't show anyone how they could use this to modify a style loader.

**Comment by billypon** [comment]
@with-heart OK, I will do it ASAP.

**Comment by billypon** [comment]
@with-heart I have added a use case in `api.md`.

**Comment by with-heart** [comment]
Hi @billypon, sorry for taking so long to get back to you. It's been a busy month. 

The use case looks great! Could you rebase changes from `master` and I'll get this merged?

**Comment by billypon** [comment]
@with-heart I have updated my commit

**Comment by with-heart** [comment]
Awesome! Thank you! I'll get this published asap

**Comment by with-heart** [comment]
Added you to our contributors list! Thanks for the contribution :)

**Pull request merged**
