### PR TITLE
feat: add setWebpackPublicPath

### LINKED ISSUE #154: how to configure publicPath?
how to configure publicPath?

### PR DESCRIPTION
**Pull request by gfafei**
fixes #154

### CODE REVIEW

**Comment by with-heart** [comment]
Hi @gfafei! I've rebased in the latest changes from `master` so we can get this merged! Thanks for the contribution :)

**Comment by with-heart** [comment]
Published as `customize-cra@0.7.0`. Thanks again!

**Comment by fireairforce** [comment]
@gfafei why this config to add a prefix `/` in the path?

**Comment by fireairforce** [comment]
> @gfafei why this config to add a prefix `/` in the path?

i want to use a cdn site...so i want to remove this `/`

**Comment by gfafei** [comment]
@fireairforce it's just a function with no dependency, maybe you can just write your own in config-override.js, instead of importing from the package

**Pull request merged**
