### PR TITLE
feat: add stylus-loader customizer

### PR DESCRIPTION
**Pull request by DayDarkDark**
I just wanted to use stylus , so I copied "setLessLoader"

### CODE REVIEW

**Comment by with-heart** [comment]
Hi @DayDarkDark, sorry for not getting back to you. I don't use `stylus`, so I'm not sure how I could test this. Are you using this in a project currently?

**Comment by with-heart** [comment]
Going to close this since I haven't heard back. Feel free to re-open.

**Comment by dehimer** [comment]
It is still actual.

**Comment by DayDarkDark** [comment]
@with-heart  I'm back, It can work, I use it in my projiect

**Pull request closed without merging**
