### PR TITLE
feat: implement setWebpackTarget

### PR DESCRIPTION
**Pull request by jthistle**
As per: https://webpack.js.org/configuration/target/

This can be useful for things like Electron apps. I've tested this with one of my own apps and it seems to work as expected.

### CODE REVIEW

**Comment by with-heart** [comment]
Hi @jthistle! Thanks for the feature! I've added you to the `customize-cra` contributors list in our `readme` :)

**Comment by jthistle** [comment]
Thanks for merging this! And for the package as well of course, it's very useful :)

**Comment by with-heart** [comment]
I'm just the maintainer! This project was built by many people working together, such as yourself! I'll get this published shortly

**Comment by with-heart** [comment]
It's published under `0.6.0`! Thanks again!

**Pull request merged**
