### PR TITLE
feat: add http/https cases to setWebpackPublicPath

### PR DESCRIPTION
**Pull request by fireairforce**
fix the [issue#168](https://github.com/arackaf/customize-cra/issues/168)

### CODE REVIEW

**Comment by with-heart** [comment]
Hi @fireairforce, thanks for the PR! I added a commit that adds tests for the new `http`/`https` cases. Will merge and get that published shortly.

**Comment by fireairforce** [comment]
OK

**Comment by fireairforce** [comment]
I hope that you can aslo update the README.md, i see some issues on how to set outputpath

**Comment by fireairforce** [comment]
Hello,Can you please publish this pr...i need to use this in my project...thx

**Comment by with-heart** [comment]
Hi @fireairforce, sorry about the delay. This is published as `customize-cra@0.8.0`.

**Pull request merged**
